# Generated by Django 5.0.3 on 2024-06-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0003_record_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
