# Generated by Django 5.0.3 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0004_rename_user_id_record_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certifications/')),
                ('description', models.TextField()),
            ],
        ),
    ]
