# Generated by Django 5.0.3 on 2024-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0005_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
