# Generated by Django 5.0.3 on 2024-07-02 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0006_alter_record_distance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='image',
            new_name='walk_image',
        ),
        migrations.AddField(
            model_name='certification',
            name='archive_image',
            field=models.ImageField(null=True, upload_to='archive/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
